# Generated by Django 3.2.4 on 2021-07-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
